name: Update Changelog

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'CHANGELOG.md'  # Prevent infinite loops
      - '.github/workflows/changelog.yml'

  workflow_dispatch:  # Allow manual triggering

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for changelog generation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --unreleased --prepend CHANGELOG.md

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet CHANGELOG.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to CHANGELOG.md"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "CHANGELOG.md has been updated"
          fi

      - name: Commit changelog
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG.md

          Auto-generated changelog from conventional commits

          Co-Authored-By: git-cliff <noreply@git-cliff.org>"

      - name: Push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git push
